apiVersion: v1
kind: Service
metadata:
  name: {{ include "cap.fullname" . }}-web
  labels:
    {{- include "cap.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "cap.name" . }}
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP