apiVersion: v1
kind: Service
metadata:
  name: {{ include "cap.fullname" . }}-minio
  labels:
    {{- include "cap.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "cap.name" . }}
    app.kubernetes.io/component: minio
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: api
      port: {{ .Values.minio.service.port }}
      targetPort: api
      protocol: TCP